# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/unknown/Documents/XKineticEngine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/unknown/Documents/XKineticEngine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unknown/Documents/XKineticEngine/CMakeFiles /home/unknown/Documents/XKineticEngine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/unknown/Documents/XKineticEngine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named XKCore

# Build rule for target.
XKCore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XKCore
.PHONY : XKCore

# fast build rule for target.
XKCore/fast:
	$(MAKE) $(MAKESILENT) -f XKCore/CMakeFiles/XKCore.dir/build.make XKCore/CMakeFiles/XKCore.dir/build
.PHONY : XKCore/fast

#=============================================================================
# Target rules for targets named XKMath

# Build rule for target.
XKMath: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XKMath
.PHONY : XKMath

# fast build rule for target.
XKMath/fast:
	$(MAKE) $(MAKESILENT) -f XKMath/CMakeFiles/XKMath.dir/build.make XKMath/CMakeFiles/XKMath.dir/build
.PHONY : XKMath/fast

#=============================================================================
# Target rules for targets named XKVulkan

# Build rule for target.
XKVulkan: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XKVulkan
.PHONY : XKVulkan

# fast build rule for target.
XKVulkan/fast:
	$(MAKE) $(MAKESILENT) -f XKVulkan/CMakeFiles/XKVulkan.dir/build.make XKVulkan/CMakeFiles/XKVulkan.dir/build
.PHONY : XKVulkan/fast

#=============================================================================
# Target rules for targets named XKDirectX12

# Build rule for target.
XKDirectX12: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XKDirectX12
.PHONY : XKDirectX12

# fast build rule for target.
XKDirectX12/fast:
	$(MAKE) $(MAKESILENT) -f XKDirectX12/CMakeFiles/XKDirectX12.dir/build.make XKDirectX12/CMakeFiles/XKDirectX12.dir/build
.PHONY : XKDirectX12/fast

#=============================================================================
# Target rules for targets named XKinetic

# Build rule for target.
XKinetic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XKinetic
.PHONY : XKinetic

# fast build rule for target.
XKinetic/fast:
	$(MAKE) $(MAKESILENT) -f XKinetic/CMakeFiles/XKinetic.dir/build.make XKinetic/CMakeFiles/XKinetic.dir/build
.PHONY : XKinetic/fast

#=============================================================================
# Target rules for targets named XKEditor

# Build rule for target.
XKEditor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 XKEditor
.PHONY : XKEditor

# fast build rule for target.
XKEditor/fast:
	$(MAKE) $(MAKESILENT) -f XKEditor/CMakeFiles/XKEditor.dir/build.make XKEditor/CMakeFiles/XKEditor.dir/build
.PHONY : XKEditor/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... XKCore"
	@echo "... XKDirectX12"
	@echo "... XKEditor"
	@echo "... XKMath"
	@echo "... XKVulkan"
	@echo "... XKinetic"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

